### ISSUE TITLE
header plugin before tsc plugin

### ISSUE THREAD

**Issue by dabbank** [tracker1/gulp-header#13]
gulp.src(tsfiles)
            .pipe(plugins.header("var test = 666;"))
            .pipe(partials.errorPipe())
            .pipe(plugins.tsc(
                {
                    allowBool: true,
                    out: CONFIG.DIST.JS.FILES.APP(),
                    sourcemap: doUseSourceMaps,
                    sourceRoot: doUseSourceMaps ? "/" : null,
                    target: ecmaScriptVersion
                }))
            .pipe(plugins.header("var test = 555;"))
            ;

will do var test = 555 but not var test = 666.
Is it somehow related to the TypeScript plugin?

Any idea ?

**Comment by tracker1** [comment]
@dabank will have to test this... I have no idea why this wouldn't work as expected...  I'm not familiar with typescript.

**Comment by tracker1** [comment]
Okay, this should be working in `1.5.2` ... regarding multiple gulp-header statements in a pipeline.
