### ISSUE TITLE
two times running header plugin

### ISSUE THREAD

**Issue by dabbank** [tracker1/gulp-header#14]
.pipe(plugins.header("test")
  .pipe(plugins.header("test2")

will only write:    test

**Comment by madhums** [comment]
this works fine

**Comment by madhums** [comment]
@dabbank can you test it on 1.5.0 version?

**Comment by tracker1** [comment]
@dabbank this should be corrected on the current release `1.5.1` can you confirm?

**Comment by tracker1** [comment]
Okay, this seems to be working for me, if it's still an issue, please reopen.
