### ISSUE TITLE
Throw errors on header with '<%

### ISSUE THREAD

**Issue by Unkz** [tracker1/gulp-header#15]
I have tried to add header with somethig like that:
var HeaderTXT = '<% Ala ma asa %>\n';
gulp.src(srcfiles)
            .pipe(gulp_header(HeaderTXT))
            .pipe(gulp.dest(destfolder));
It throws result "SyntaxError: Unexpected identifier".
Changing HeaderTXT to '< Ala ma asa >\n'; prevents throwing an error.
Can I escape sequence '<%' or '<%=' ?

**Comment by tracker1** [comment]
It's `'<%= value %>'` or `'${ value }'` ...  This module uses gulp-util, which in turn uses lodash.template, so anything lodash.template supports you should be able to use.
