### ISSUE TITLE
Error when gulp.src does not find any files

### ISSUE THREAD

**Issue by adgoncal** [tracker1/gulp-header#17]
```javascript
gulp.task('taskname', function() {
  return gulp.src('*.html')
    .pipe(header('Hello'));
});
```

When there are no html files in '*.html', it throws the following error:
```
node_modules/gulp-header/index.js:58
    var file = _file.clone({ contents: false });
                    ^
TypeError: Cannot read property 'clone' of undefined
```

Apparently, <code>TransformStream</code> never gets called, but <code>EndStream</code> does. <code>_file</code> is undefined and, therefore, does not have a <code>clone</code> property.

Proposed solution is to add the following code to the beginning of <code>EndStream</code> function:
```javascript
if(!_file) {
  return cb();
}
```

**Comment by mrtnbroder** [comment]
+1 we get the same error.

**Comment by ravenscar** [comment]
+1 same error in our build scripts

**Comment by JuliaRechkunova** [comment]
The same error. Returned to 1.2.2 version.

**Comment by tracker1** [comment]
Looks like the changes for `1.5.1` should resolve this, can you confirm?

**Comment by adgoncal** [comment]
It looks good. Thanks.
