### ISSUE TITLE
gulp-header only works on one file

### ISSUE THREAD

**Issue by jacobboland** [tracker1/gulp-header#18]
Since the 1.5 release, gulp-header stopped working on multiple streams of files.

```
gulp.src('/js/**/.js') // where multiple js files exist
       .pipe(header('use strict;'))
       .dest(...);
```

This does not throw an error, but the result is only the last file in the stream gets handled. 

The reason:

_file is declared in the module and expected to be per stream, but it is continuously overridden until EndStream runs with only the final file.

**Comment by kobezzza** [comment]
+1

**Comment by adamkdean** [comment]
Also having this issue.
