### ISSUE TITLE
1.5.0 fails if the file has `\r\n` line separators

### ISSUE THREAD

**Issue by ibc** [tracker1/gulp-header#20]
If the source file contains `\r\n` symbols (instead of just `\n`) then gulp-header produces a corrupt output in which part of the original source file is suppressed. Related to 33c17a37a42e71d13d1e83b8c54b65f53f30b951.

I've tested that 1.5.0 works correctly if the source file has just `\n`.

**Comment by kobezzza** [comment]
+1
