### ISSUE TITLE
Please add source map support

### ISSUE THREAD

**Issue by joacim-boive** [tracker1/gulp-header#27]
I can't get gulp-sourcemap to work with your plugin.

I suppose the reason is that you don't support the gulp-sourcemap plugin:
https://github.com/floridoo/gulp-sourcemaps/wiki/Plugins-with-gulp-sourcemaps-support

Pretty please, with sugar on top - add it.

**Comment by destroyerofbuilds** [comment]
@joacim-boive this project does support source maps: https://github.com/tracker1/gulp-header/blob/master/index.js#L8
