### ISSUE TITLE
Source sourcemap file added to output sourcemap

### ISSUE THREAD

**Issue by SeanSobey** [tracker1/gulp-header#28]
Hi, thanks for the great plugin.

I have a gulp task like so:

**gulp.src(src)
.pipe(plugins.sourcemaps.init())
.pipe(plugins.concatUtil(outFileName))
.pipe(plugins.header(_banner, { pkg: pkg }))
.pipe(plugins.sourcemaps.write(".", { includeContent: false, sourceRoot: sourceRoot + plugins.path.sep }));**

I expect the source mapping to only include files from 'src', but the concat generated file is being added in by gulp-header along with them.

This appears to be due to the line:
<code>
if (file.isBuffer()) {
      concat.add(filename, new Buffer(template));
    }
</code>

This can be fixed like so:
<code>
if (file.isBuffer()) {
      concat.add(null, template);
    }
</code>

This is suggested by [concat-with-sourcemaps](https://www.npmjs.com/package/concat-with-sourcemaps):
> for content without a file reference, e.g. a license comment.

**Comment by philkunz** [comment]
So does gulp-header support gulp-sourcemaps?

**Comment by SeanSobey** [comment]
Yes, except for the issue I mentioned it does have sourcemap support via [concat-with-sourcemaps](https://www.npmjs.com/package/concat-with-sourcemaps).

There are quite a few plugins that support sourcemaps that are not on that list. I suggest checking the source codes for reliable evidence that plugins have the feature.

**Comment by tracker1** [comment]
Made the change, there was a bug with streams, which I corrected...
