### ISSUE TITLE
Linting and syntax tools show error in js files present at tests/fixtures/

### ISSUE THREAD

**Issue by Kasahs** [tracker1/gulp-header#31]
The files have .js extension and (obviously) contain syntactically incorrect js. Maybe rename the files to .txt?

**Comment by tracker1** [comment]
I've renamed them, and updated the tests... there's some other stuff I've been trying to find the time for so I can get a new publish up.

**Comment by tracker1** [comment]
okay, 1.8.2 should now be working...

**Comment by Kasahs** [comment]
@tracker1 cool.
