### ISSUE TITLE
Crashes when the source file doesn't physically exist

### ISSUE THREAD

**Issue by RIAstar** [tracker1/gulp-header#36]
Affects: v1.8.3

When a file in the stream doesn't exist on disk (quite a common scenario in a Gulp pipeline), `gulp-header crashes` because the path can't be found.

I tracked the issue down to https://github.com/tracker1/gulp-header/commit/7feb21151e9101baa47a5ce61d3d6dbc7b975b08#diff-168726dbe96b3ce427e7fedce31bb0bcR38

I guess it should be enough to simply check for existence of the file:
```
if (fs.existsSync(file.path) && fs.lstatSync(file.path).isDirectory())
```
works for my use case.

**Comment by Ravoltz** [comment]
Please note that fs.exists and fs.existsSync are deprecated.
https://nodejs.org/dist/latest-v6.x/docs/api/fs.html#fs_fs_existssync_path

**Comment by fidian** [comment]
This is apparently the same issue as #37

**Comment by RIAstar** [comment]
Think so. But I got here first ;)
I'll close it since the other one seems to be getting all the attention.

**Comment by falsandtru** [comment]
If #37 is a same issue, and this issue will be reopened, I'll set this issue as a canonical issue, and closing #37 because this issue has more details. @RIAstar can you?

**Comment by aboydDD** [comment]
subscribing to this solution as if this is fixed - the issue won't happen in gulp-template-cache and won't matter if gulp-template-cache has 1.x set for gulp-header.

gulp-template-cache aren't changing their package.json gulp-header version
therefore just waiting for this issue to be resolved.

temporary fix is adding gulp-header:1.8.2 in your project package.json to stop builds failing but this isn't a long term solution.

**Comment by don4of4** [comment]
I hate to state the obvious, but this is rapidly becoming a very urgent issue.  Any chance this will be patched by Monday?

**Comment by VictorLeach96** [comment]
The build system for SemanticUI is broken due to this.

**Comment by 06wj** [comment]
+1

**Comment by el-davo** [comment]
Tried this morning. This is still an issue for us. Did you publish the fix to npm?

**Comment by paulsouche** [comment]
+1

**Comment by lukasbestle** [comment]
+1

**Comment by jscriptcoder** [comment]
Same issue here... Solution suggested by @RIAstar works fine for me

**Comment by greenarr0w** [comment]
same Problem here, please fix asap

**Comment by stepler** [comment]
++++++++1

**Comment by el-davo** [comment]
You can temporarily add this you your package.json devDependencies to fix the issue

"gulp-header": "1.8.2"

**Comment by mryellow** [comment]
Merge and deploy `1.8.4`, no need to worry about the commit history being rebased, just fix it.

There are a large number of broken builds out there and you're going to end up with a large number of users pinning their version at `1.8.2`, meaning any critical fixes will no longer be deployed to these installs.

**Comment by linsolas** [comment]
+1

**Comment by PatrikElfstrom** [comment]
Yes, please fix

**Comment by smithwib** [comment]
+1

**Comment by tracker1** [comment]
Okay, removed the specific detections for actual file existance (1.8.6), and adjusted detection against vinyl's isDirectory/isStream/isBuffer, etc.

Should correct all outstanding issues.

**Comment by tracker1** [comment]
See #44
