### ISSUE TITLE
1.8.3 throws an exception

### ISSUE THREAD

**Issue by falsandtru** [tracker1/gulp-header#37]
1.8.3 https://travis-ci.org/falsandtru/spica/builds/138314049
1.8.2 https://travis-ci.org/falsandtru/spica/builds/138318418

**Comment by fidian** [comment]
This is due to commit 6d3506e4a9be309390275c1aa580a54496af8417

We use gulp-angular-templatecache to build our assets.  With the release that happened only 2 hours ago, we now can not build our application.

```
gulp.task("templates", function(){
    var result = gulp.src(templatePaths())
        .pipe(templateCache("gisnep-ui-templates.js", {module: "gisnepUi"}))
        .pipe(concat("gisnep-ui-templates.js"))
        .pipe(gulp.dest("www"));
    return result;
});
```

**Comment by DaniVarga** [comment]
+1

**Comment by ascartabelli** [comment]
Yes, that [`lstatSync.isDirectory`](https://github.com/tracker1/gulp-header/commit/6d3506e4a9be309390275c1aa580a54496af8417#diff-168726dbe96b3ce427e7fedce31bb0bcR38) check raises an exception if you have a in-memory stream.

**Comment by DaniVarga** [comment]
how to fix

```
npm uninstall gulp-header
npm install gulp-header@1.8.2
```

**Comment by dstoreng** [comment]
+1

**Comment by basvis** [comment]
+1

**Comment by kwypchlo** [comment]
+1

**Comment by fsmaamo** [comment]
+1

**Comment by frankkoenigstein** [comment]
+1

**Comment by s2x** [comment]
+1

**Comment by el-davo** [comment]
+1

**Comment by mjohnston32** [comment]
+1

**Comment by kyle-long** [comment]
+1

**Comment by baelish** [comment]
+1

**Comment by nkreter** [comment]
+1

**Comment by myshov** [comment]
:+1:

**Comment by myshov** [comment]
+1

**Comment by Trufi** [comment]
+1

**Comment by andymost** [comment]
+1

**Comment by RLRR** [comment]
+1

**Comment by kneumei** [comment]
+1

**Comment by cmurken** [comment]
+1

**Comment by ArtZanko** [comment]
+1

**Comment by lastw** [comment]
+1

**Comment by falsandtru** [comment]
If #36 is a same issue, and it will be reopened, I'll set #36 as a canonical issue and closing this issue because its issue has more details. @RIAstar can you?

**Comment by RayProud** [comment]
+1

**Comment by vfiodarau** [comment]
+1

**Comment by ibc** [comment]
+1

**Comment by ibc** [comment]
This is the cause of the issue: https://github.com/tracker1/gulp-header/pull/34/files#diff-168726dbe96b3ce427e7fedce31bb0bcR35

It fails when, instead of a file, a in-memory stream is given:

```js
gulp.task('browserify', function() {
	return browserify([path.join(__dirname, PKG.main)]).bundle()
		.pipe(vinyl_source_stream(PKG.name + '.js'))
		.pipe(vinyl_buffer())
		.pipe(header(BANNER, BANNER_OPTIONS))
		.pipe(gulp.dest('dist/'));
});
```

**Comment by Devqon** [comment]
+1

**Comment by danivek** [comment]
+1

**Comment by robinj** [comment]
+1

**Comment by twinser** [comment]
+1

**Comment by siddv** [comment]
+1

**Comment by devfive** [comment]
+1

**Comment by Durairaj** [comment]
+1

**Comment by blackstylle** [comment]
+1

**Comment by pgrzeszczak-neducatio** [comment]
+1

**Comment by jeanp** [comment]
+1

**Comment by leyendecker** [comment]
+1

**Comment by jakub-g** [comment]
Guys, if you want to subscribe to the thread, click "subscribe" in the sidebar on the bottom right. No need to spam everyone, 30+ emails in 5 hours is probably enough for the maintainer to realize something is wrong :)

**Comment by jakecr** [comment]
`npm unpublish`!

**Comment by pekkahaka** [comment]
This broke at least gulp-angular-templatecache. This is what you get when you don't use exact version numbers in your package.json (or use modules that don't use exact version numbers, as in this case).

**Comment by ibc** [comment]
> This is what you get when you don't use exact version numbers in your package.json

No. This is what you get when a module does not have test units covering all the use cases. Incrementing the version TINY number is supposed for bug fixes (although in this case it means "a new bug is introduced"). Others should be able to rely in any X.Y.Z if X does not change (as SEMVER states).

**Comment by pekkahaka** [comment]
>  Others should be able to rely in any X.Y.Z if X does not change

In ideal world - yes. In reality - no. These  modules are done by people and people make mistakes - and you should be prepared for it.
Nevertheless i think this is not a right please for this discussion.

**Comment by francisdb** [comment]
This also breaks semantic ui builds

**Comment by prettycode** [comment]
+1

**Comment by shuk** [comment]
+1

**Comment by hsablonniere** [comment]
+1

**Comment by tykowale** [comment]
+1

**Comment by grishchenkoa** [comment]
+1

**Comment by dazewell** [comment]
+1

**Comment by jooleeunc** [comment]
+1

**Comment by milesap** [comment]
+1000

**Comment by clok** [comment]
+1

**Comment by chrisiconolly** [comment]
:+1:

**Comment by thehindenburg** [comment]
:+1:

**Comment by kevinphelps** [comment]
+1

**Comment by edclement** [comment]
:+1:

**Comment by Borfswitch** [comment]
+1

**Comment by edclement** [comment]
see comment on this commit for fix:
https://github.com/tracker1/gulp-header/commit/d2687721841f976191839b8258bca9f732798d55

**Comment by petejohanson** [comment]
Seriously, everybody stop blindly +1-ing this issue. Some of us are subscribed so we can get meaningful updates when this is fixed. There is absolutely no question this is an important bug, and one or ten more +1s isn't going to help anything. 

If you want to, use the new-ish GH feature to thumbs up the initial comment to voice what you're feeling. Stop spamming the issue

**Comment by jaylittle** [comment]
We worked around this issue locally by adding an npm-shrinkwrap.json file containing the following content:

    {
      "dependencies": {
        "gulp-header": {
          "version": "1.8.2",
          "from": "gulp-angular-templatecache@1.8.0"
        }
      }
    }

**Comment by candyam5522** [comment]
+1

**Comment by feedthefire** [comment]
+1 happy friday!

**Comment by francisdb** [comment]
To make it easier to find this issue I'm posting the actual trace you get

```
fs.js:839
  return binding.lstat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, lstat '/var/lib/jenkins/jobs/github/jobs/xxx/branches/master/workspace/public/semantic/components/semantic.min.js'
    at Error (native)
    at Object.fs.lstatSync (fs.js:839:18)
    at DestroyableTransform.TransformStream [as _transform] (/var/lib/jenkins/jobs/github/jobs/xxx/branches/master/workspace/node_modules/gulp-header/index.js:38:12)
```

**Comment by evankleist** [comment]
+1

**Comment by anipendakur** [comment]
+1

**Comment by kelvinw88** [comment]
+1

**Comment by gigablox** [comment]
erg mah gerggg fix itttt

**Comment by ibc** [comment]
@gigablox do you know reading?

**Comment by gigablox** [comment]
@ibc I met him once, nice guy.

**Comment by maenthoven** [comment]
+1

**Comment by don4of4** [comment]
Output if you might find it useful: 
```
[02:36:25][Step 1/2] fs.js:691
[02:36:25][Step 1/2]   return binding.lstat(pathModule._makeLong(path));
[02:36:25][Step 1/2]                  ^
[02:36:25][Step 1/2] Error: ENOENT, no such file or directory '/home/app/et-main/client/.tmp/serve/app/templateCacheHtml.js'
[02:36:25][Step 1/2]     at Object.fs.lstatSync (fs.js:691:18)
[02:36:25][Step 1/2]     at DestroyableTransform.TransformStream [as _transform] (/home/app/et-main/node_modules/gulp-header/index.js:38:12)
[02:36:25][Step 1/2]     at DestroyableTransform.Transform._read (/home/app/et-main/node_modules/gulp-header/node_modules/readable-stream/lib/_stream_transform.js:159:10)
[02:36:25][Step 1/2]     at DestroyableTransform.Transform._write (/home/app/et-main/node_modules/gulp-header/node_modules/readable-stream/lib/_stream_transform.js:147:83)
[02:36:25][Step 1/2]     at doWrite (/home/app/et-main/node_modules/gulp-header/node_modules/readable-stream/lib/_stream_writable.js:313:64)
[02:36:25][Step 1/2]     at writeOrBuffer (/home/app/et-main/node_modules/gulp-header/node_modules/readable-stream/lib/_stream_writable.js:302:5)
[02:36:25][Step 1/2]     at DestroyableTransform.Writable.write (/home/app/et-main/node_modules/gulp-header/node_modules/readable-stream/lib/_stream_writable.js:241:11)
[02:36:25][Step 1/2]     at write (/home/app/et-main/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
[02:36:25][Step 1/2]     at flow (/home/app/et-main/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
[02:36:25][Step 1/2]     at DestroyableTransform.pipeOnReadable (/home/app/et-main/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
```

**Comment by falsandtru** [comment]
Merge into #36.

**Comment by tracker1** [comment]
see #44
