### ISSUE TITLE
1.8.3 – Potentially unhandled rejection [2] Error: no writecb in Transform class

### ISSUE THREAD

**Issue by volkish** [tracker1/gulp-header#41]
Task:
`gulp.task('components_styles', function () {
	gulp.src(paths.components.styles)
		.pipe(less({
			paths: [
				'./public_html/static/assets/stylesheets'
			]
		}))
		.pipe(csso())
		.pipe(header(fileHeaders))
		.pipe(rename(fixComponentPath))
		.pipe(gulp.dest('./public_html/static/assets/stylesheets/Components'));
});`

**Comment by gtanner** [comment]
Encountered this as well, pinned our dep to 1.7.1 for now while we wait for this to be fixed.

**Comment by alessandrovaccaro** [comment]
Is this issue potentially be the cause of this [one](https://github.com/swagger-api/swagger-ui/issues/2227) on swagger-ui?

**Comment by tracker1** [comment]
is this still happening with 1.8.4?  I pushed the patch wrt the pending pull request...

**Comment by tracker1** [comment]
Should be fixed in 1.8.4/5

**Comment by alessandrovaccaro** [comment]
@tracker1 I have tried it on swagger-ui and it looks good, thank you!

**Comment by tracker1** [comment]
see #44
