### ISSUE TITLE
Place the header after @charset

### ISSUE THREAD

**Issue by yoanmalie** [tracker1/gulp-header#48]
Hello !
I use your gulp-header for my .js and .css file.

But in CSS, at the first line i have sometime the @charset="UTF-8" rule. gulp-header add a header at the top of the file so my @charset is not valid, because it need to be at the first line, before anything.

It could be awesome if we can have a new option `charset`, false by default. And when it's true, it check if there are a @charset rule, and place the header one line after.

Thanks :smiley:

**Comment by tracker1** [comment]
Couldn't you just put the `@charset="UTF-8"` at the beginning of your header?

**Comment by yoanmalie** [comment]
Hi,
Yeah it work but it's a bit weird, because this charset rule need to be in the source, we don't know which charset is used before looking gulpfile.js. I think it's not clear and not a good practice to do like that.

**Comment by tracker1** [comment]
You could also make it a parameter passed into the options, and have it an empty string by default...
