### ISSUE TITLE
BOM is not preserved at start of file if coming from gulp-sass compressed

### ISSUE THREAD

**Issue by markspolakovs** [tracker1/gulp-header#52]
I have a *really* weird bug that is a combination of gulp-sass and gulp-header.

**Steps to reproduce:**

1. Have a .scss file with non-ASCII characters (◼ for example)
2. Pass it through gulp-sass with `{outputStyle: 'compressed'}` and gulp-header
3. Look at the output in a hex editor

![2017-09-15_21-50-13](https://user-images.githubusercontent.com/2904440/30500734-e9c46356-9a5f-11e7-9c51-943c4a41176a.png)

**Expected behaviour:**

gulp-sass adds a Unicode BOM (`EF BB BF` in UTF-8), and gulp-header moves it to the beginning of the file.

**Actual behaviour:**

The BOM is maintained in the file but *after* the header, meaning it gets treated as a regular (invalid) Unicode character.

I could not reproduce this without gulp-sass set to compressed output, even if the source file to gulp-header had a UTF-8 BOM in it. In non-compressed output, gulp-sass adds a `@charset "UTF-8";` to the output instead of a BOM.

From stepping through the gulp pipeline with a debugger, the BOM is already present when it reaches gulp-header, however it should be moved to the beginning of the output file.

Repro repo: https://github.com/markspolakovs/gulp-sass-header-bom-repro. Original repo where we encountered the issue (and broke the build): https://github.com/VolunteerLiveTeam/VLT-Reddit-Stylesheet

**Comment by tracker1** [comment]
This module doesn't manipulate the original text... would suggest stripping the BOM from earlier output and putting it at the top of the header if you *REALLY* want it in place...

Node's streams do not have any special handling for BOM, and leave them as-is, and sometimes fail on them... it would be inappropriate for this module to do such manipulation.
