### ISSUE TITLE
extend is not defined

### ISSUE THREAD

**Issue by heroqu** [tracker1/gulp-header#56]
Hi!

I've tried to use a template with pre-populated file.data and the plugin had broken, because extend function on line 25 is never defined:

``` bash
.../node_modules/gulp-header/index.js:25
data = extend(data, file.data);
^

ReferenceError: extend is not defined
```

Btw the `gulp-footer` is working fine with the identical setup, as it uses Object.assign() instead. 

Here is a gulpfile to reproduce: 

``` javascript
const gulp = require('gulp')
const data = require('gulp-data')
const header = require('gulp-header')

gulp.task('default', () =>
  gulp
    .src('src/sample.txt')
    .pipe(data(file => ({ x: 'x' })))
    .pipe(header('<%= file.data.x %>', {}))
    .pipe(gulp.dest('dest'))
)
```
And thanks for you plugin.

Sergey M.

**Comment by demurgos** [comment]
Thank you for reporting this issue. This looks like a bug: I cannot find where `extend` is defined.
You are right that it should be `Object.assign`.

`extend` was removed in https://github.com/tracker1/gulp-header/commit/e6a6e33e780ce458bcac1d3109ceb17ad24efd16 but it seems that it was missed in some parts.
