### ISSUE TITLE
gulp-sourcemaps support

### ISSUE THREAD

**Issue by ksmithut** [tracker1/gulp-header#7]
Have you considered adding [sourcemaps](https://www.npmjs.org/package/gulp-sourcemaps) support?

**Comment by tracker1** [comment]
Looks like you should just be able to use [gulp-sourcemaps](https://www.npmjs.com/package/gulp-sourcemaps)

```js
var gulp = require("gulp");
var sourcemaps = require("gulp-sourcemaps");
var header = require("gulp-header");
var headerText = require("fs").readSync(__dirname + "/txt/header.js", {encoding:utf8});

gulp.task("default", function () {
  return gulp.src("src/**/*.js")
    .pipe(sourcemaps.init())
    ......
    .pipe(header(headerText))
    .pipe(sourcemaps.write("."))
    .pipe(gulp.dest("dist"));
});
```

**Comment by contra** [comment]
@tracker1 No, using gulp-sourcemaps won't make sourcemaps somehow work with this. You should reopen this.

**Comment by nervo** [comment]
:+1: on supporting sourcemaps

**Comment by KenPowers** [comment]
:+1:  As well.

**Comment by kasperisager** [comment]
Just adding another :+1:

**Comment by vrockai** [comment]
I've just left the gulp-header plugin today and used (ugly) gulp-concat workaround (just to prepend licence string) instead, only because of this issue. Big :+1: to resolving this.

**Comment by JeremyJames** [comment]
:+1:

**Comment by JeremyFagis** [comment]
:+1: :+1:

**Comment by tracker1** [comment]
@vrockai any chance you could post your gulpfile with concat that is working... I haven't had a chance to dig through this, but will need it myself in a few weeks.

**Comment by vrockai** [comment]
@tracker1 , I'm just using temporary file; ugly, but working:
https://github.com/vrockai/hawkular-ui-components/commit/83aac479623bbc364812411e5210be5d6a134afa#diff-b20c7230de4da834e815c06534cab810R124

**Comment by madhums** [comment]
Sent a PR https://github.com/tracker1/gulp-header/pull/16
